version: 2.1

jobs:
  build:
  docker:
    - image: docker:git
  environment:
    IMAGE_NAME: virtualstock/docker-git
    IMAGE_TAG: "0.1"
  steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Docker registry login
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Install dockerize
        command: |
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
        environment:
          DOCKERIZE_VERSION: v0.3.0
    - run:
        name: Wait for docker host
        command: dockerize -wait $DOCKER_HOST -timeout 2m
    - run:
        name: Build image
        command: docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - run:
        name: push to tag
        command: docker push ${IMAGE_NAME}:${IMAGE_TAG}
    - run:
        name: push to latest
        command: |
          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
